"""Compile the newsletter's recurring sections into standing reference pages.

    python scripts/build_companions.py            # write companions/
    python scripts/build_companions.py --check    # exit 1 if companions/ is stale

Reads `archive/` (the synced newsletter) and writes generated pages under
`companions/`. Each is one recurring section of the newsletter, pulled out
of every edition it appeared in and laid end to end, newest first:

- `praxis.md`       Research praxis: one note on how to read, write or judge evidence
- `glossary.md`     Disambiguation corner: terms that get swapped for each other
- `methods.md`      the methods corner, methods notes and research-history pieces
- `datasets.md`     One dataset to open
- `researchers.md`  Researchers worth following, one entry per person
- `reading.md`      every paper and report the newsletter recommended, by edition
- `books.md`        every book, documentary and long read, by edition
- `tools.md`        tools, platforms and free resources, by edition

These are the parts of an edition that outlive it. A reader who wants the
poverty-line note does not care that it ran in May 2026; they want the note.
Everything here carries a link back to the edition it came from, so nothing is
quoted without its source, and nothing is edited: the text is the newsletter's,
including its typos.

Where the archive uses different heading conventions in different years (the
2024-25 editions use `###` sub-headings, the 2025-26 ones a bold first line,
and the section title sometimes carries the note's title after a colon), the
rules in `entries()` reconcile them. Add a case there rather than editing the
generated files, which are overwritten on every run.
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARCHIVE = ROOT / "archive"
OUT = ROOT / "companions"

HEAD = re.compile(r"^(#{2,4}) (.+)$", re.M)
EMOJI = re.compile(r"[\U0001F000-\U0001FAFF☀-➿⬀-⯿️]")
GENERATED = "Generated by `scripts/build_companions.py` from `archive/`; edit the source, not this file."

# Which section headings feed which companion. Matching is case-insensitive
# substring, after emoji and bold markers are stripped.
SECTIONS = {
    "praxis": ("research praxis",),
    "glossary": ("disambiguation",),
    "methods": ("methods corner", "methods note", "research history"),
    "datasets": ("one dataset", "dataset to open"),
    "researchers": ("researchers worth following", "researchers to follow"),
    "reading": ("worth reading", "must-reads", "one paper worth reading"),
    "books": ("one book", "two books", "books", "documentary"),
    "tools": ("tools &", "resources & tools", "resource worth keeping", "platform to explore"),
}

# Prefixes to strip from a section heading to leave the note's own title.
PREFIX = {
    "praxis": r"^research praxis( with varna)?\s*[:\-–—]?\s*",
    "glossary": r"^disambiguation( corner)?\s*[:\-–—]?\s*",
    "methods": r"^(a small methods corner|a methods note|research history)\s*[:\-–—]?\s*",
    "datasets": r"^one dataset to open\s*[:\-–—]?\s*",
}


# --------------------------------------------------------------------------- parsing

def front_matter(md: str) -> dict:
    m = re.match(r"---\n(.*?)\n---\n", md, re.S)
    fm = {}
    if m:
        for line in m.group(1).splitlines():
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip().strip('"')
    return fm


def clean(h: str) -> str:
    """A heading as a title: no emoji, no bold markers, no trailing colon."""
    h = EMOJI.sub("", h).replace("**", "")
    h = re.sub(r"\s+", " ", h).strip()
    return h.strip(" :").strip()


def month_year(d: str) -> str:
    y, m, _ = (int(x) for x in d.split("-"))
    return date(y, m, 1).strftime("%B %Y")


def long_date(d: str) -> str:
    y, m, dd = (int(x) for x in d.split("-"))
    return f"{dd} {date(y, m, dd).strftime('%B %Y')}"


def sections(md: str) -> list[tuple[int, str, str]]:
    """(level, heading, body) for every ##/###/#### heading in the post."""
    parts = HEAD.split(md)
    out = []
    for i in range(1, len(parts), 3):
        out.append((len(parts[i]), parts[i + 1].strip(), parts[i + 2]))
    return out


def tidy(text: str) -> str:
    text = re.sub(r"!\[[^\]]*\]\([^)]*\)\n?", "", text)          # images
    text = re.sub(r"(?m)^\*[^*\n]{0,160}\*$\n?", "", text)         # figure captions
    text = re.sub(r"(?m)^👉\s*", "", text)                          # link pointers
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    text = re.sub(r"^---\n+", "", text)                             # rule left at either end
    text = re.sub(r"\n+---$", "", text)
    return text.strip()


def hits(kind: str) -> list[dict]:
    """Every matching section in every edition, newest first, with the deeper
    sections that follow it attached as `subs`."""
    words = SECTIONS[kind]
    out = []
    for f in sorted(ARCHIVE.glob("2*.md"), reverse=True):
        md = f.read_text(encoding="utf-8")
        fm = front_matter(md)
        secs = sections(md)
        for idx, (lvl, h, body) in enumerate(secs):
            ch = clean(h).lower()
            if not any(w in ch for w in words):
                continue
            subs = []
            for lvl2, h2, body2 in secs[idx + 1:]:
                if lvl2 <= lvl:
                    break
                subs.append((clean(h2), tidy(body2)))
            out.append({
                "date": fm.get("date", ""), "title": clean(fm.get("title", "")),
                "file": f.name, "type": fm.get("type", ""),
                "heading": clean(h), "body": tidy(body), "subs": subs,
            })
    return out


# --------------------------------------------------------------------------- entries

# A bold line that opens a block, with whatever follows it on the same line
# (usually the profile links) kept as the first line of the body.
BOLD_LEAD = re.compile(r"^\*\*(.+?)\*\*([^\n]*)\n+")


def lead_rest(m: re.Match) -> str:
    return re.sub(r"^[\s👉]+", "", m.group(2)).strip()


def split_blocks(body: str) -> list[str]:
    """Rules (`---`) separate entries in the 2026 editions."""
    return [b.strip() for b in re.split(r"(?m)^---$", body) if b.strip()]


def entries(kind: str, hit: dict) -> list[dict]:
    """One companion entry per note. The title comes, in order of preference,
    from the section heading after its standing prefix, from a sub-heading,
    or from a bold line that opens the block."""
    src = {"date": hit["date"], "title": hit["title"], "file": hit["file"]}
    own = re.sub(PREFIX.get(kind, r"$^"), "", hit["heading"], flags=re.I).strip(" :")
    if own.lower() in ("research praxis", "disambiguation corner"):
        own = ""
    if own and own[0].islower():
        own = own[0].upper() + own[1:]

    if own:                                     # "Research praxis: How to read a deletion rate"
        text = hit["body"]
        for h2, b2 in hit["subs"]:
            text += f"\n\n### {h2}\n\n{b2}"
        return [{**src, "name": own, "text": text.strip()}]

    if hit["subs"]:                             # "## Research praxis" then "### <title>"
        out = []
        lead = hit["body"]
        for i, (h2, b2) in enumerate(hit["subs"]):
            text = b2
            if i == 0 and lead and not lead.startswith("---"):
                text = f"{lead}\n\n{b2}"
            out.append({**src, "name": h2, "text": text.strip()})
        return out

    out = []                                    # bold first line, blocks split by rules
    for block in split_blocks(hit["body"]):
        m = BOLD_LEAD.match(block)
        if m:
            rest = lead_rest(m)
            text = (rest + "\n\n" if rest else "") + block[m.end():].strip()
            out.append({**src, "name": clean(m.group(1)), "text": text.strip()})
        else:
            out.append({**src, "name": f"{hit['heading']}, {month_year(hit['date'])}", "text": block})
    return out


def people(hit: dict) -> list[dict]:
    """Researchers: a `###` sub-heading per person in 2024-25, a bold lead
    ('Name — Affiliation') per paragraph from 2026. Names are split from
    taglines on the first dash."""
    src = {"date": hit["date"], "title": hit["title"], "file": hit["file"]}
    found = []
    if hit["subs"]:
        for h2, b2 in hit["subs"]:
            found.append((h2, b2))
    else:
        for block in re.split(r"\n\n(?=\*\*)", hit["body"]):
            m = BOLD_LEAD.match(block.strip())
            if m:
                rest = lead_rest(m)
                text = (rest + "\n\n" if rest else "") + block.strip()[m.end():].strip()
                found.append((clean(m.group(1)), text.strip()))
    out = []
    for name, blurb in found:
        parts = re.split(r"\s+[-–—]\s+", name, maxsplit=1)
        person, tagline = parts[0].strip(), (parts[1].strip() if len(parts) > 1 else "")
        if tagline:
            blurb = f"*{tagline}.*\n\n{blurb}"
        out.append({**src, "name": person, "text": blurb})
    return out


# --------------------------------------------------------------------------- writing

def source_line(e: dict) -> str:
    return f"*From [{e['title']}](../archive/{e['file']}), {e['date']}.*"


def write_notes(name: str, title: str, intro: str, items: list[dict]) -> int:
    lines = [f"# {title}", "", intro, "", GENERATED, ""]
    for e in items:
        lines += [f"## {e['name']}", "", source_line(e), "", e["text"], ""]
    (OUT / name).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(items)


def write_by_edition(name: str, title: str, intro: str, kind: str) -> int:
    """Reading, books, tools: the unit is the edition, not the item, because
    the items are short and the edition's framing is part of the point."""
    lines = [f"# {title}", "", intro, "", GENERATED, ""]
    n = 0
    for h in hits(kind):
        text = h["body"]
        for h2, b2 in h["subs"]:
            text += f"\n\n### {h2}\n\n{b2}"
            n += 1
        if not h["subs"]:
            n += max(1, len(re.findall(r"(?m)^\*\*", text)))
        when = month_year(h["date"]) if h["type"] == "edition" else long_date(h["date"])
        lines += [f"## {when}", "",
                  f"*{h['heading']}, from [{h['title']}](../archive/{h['file']}), {h['date']}.*",
                  "", text.strip(), ""]
    (OUT / name).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return n


def write_people(items: list[dict]) -> int:
    seen: dict[str, dict] = {}
    for e in items:
        key = e["name"].lower()
        if key in seen:
            seen[key]["editions"].append(e)
        else:
            seen[key] = {"name": e["name"], "text": e["text"], "editions": [e]}
    lines = ["# Researchers worth following", "",
             "Everyone the newsletter has recommended, with what it said about them and where. "
             "Alphabetical by surname; the blurb is from the most recent mention.", "", GENERATED, ""]
    for key in sorted(seen, key=lambda k: k.split()[-1]):
        p = seen[key]
        lines += [f"## {p['name']}", "", p["text"], ""]
        for e in p["editions"]:
            lines.append(f"- {source_line(e)[1:-1]}")
        lines.append("")
    (OUT / "researchers.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(seen)


def build() -> dict[str, int]:
    OUT.mkdir(exist_ok=True)
    n = {}
    n["praxis"] = write_notes(
        "praxis.md", "Research praxis",
        "Every research-practice note the newsletter has run, newest first. Each is a way of "
        "reading, writing or judging evidence that outlives the edition it appeared in. "
        "Several have a script in `tools/`; the entry says which.",
        [e for h in hits("praxis") for e in entries("praxis", h)])
    n["glossary"] = write_notes(
        "glossary.md", "Disambiguation corner",
        "Terms the newsletter has taken apart because they are routinely swapped for each other. "
        "Each entry says how the terms differ and why the difference changes a number or a policy.",
        [e for h in hits("glossary") for e in entries("glossary", h)])
    n["methods"] = write_notes(
        "methods.md", "Methods corner",
        "Short methods notes and research-history pieces: the difference between odds and "
        "likelihood, reach and impact, participation as a design property, the Hawthorne effect.",
        [e for h in hits("methods") for e in entries("methods", h)])
    n["datasets"] = write_notes(
        "datasets.md", "Datasets worth opening",
        "Datasets the newsletter has pointed readers at, with what it said to watch for in each.",
        [e for h in hits("datasets") for e in entries("datasets", h)])
    n["researchers"] = write_people([p for h in hits("researchers") for p in people(h)])
    n["reading"] = write_by_edition(
        "reading.md", "Papers and reports",
        "Everything the newsletter recommended reading, edition by edition, newest first, "
        "with the editor's take where one was given.", "reading")
    n["books"] = write_by_edition(
        "books.md", "Books, documentaries and long reads",
        "Every book, film and long read the newsletter has recommended, by edition.", "books")
    n["tools"] = write_by_edition(
        "tools.md", "Tools and free resources",
        "Platforms, datasets portals and free resources the newsletter has pointed at, by edition. "
        "Links are as published; the newsletter does not re-check them.", "tools")
    return n


def main(argv: list[str]) -> int:
    if "--check" in argv:
        before = {p.name: p.read_text(encoding="utf-8") for p in OUT.glob("*.md")}
        build()
        after = {p.name: p.read_text(encoding="utf-8") for p in OUT.glob("*.md")}
        stale = sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k))
        for k, v in before.items():          # restore, so --check has no side effects
            (OUT / k).write_text(v, encoding="utf-8")
        for k in set(after) - set(before):
            (OUT / k).unlink()
        if stale:
            print("STALE: " + ", ".join(stale) + " (run scripts/build_companions.py)")
            return 1
        print("PASS companions/ matches archive/")
        return 0
    n = build()
    print(", ".join(f"{k} {v}" for k, v in n.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
